name: Windows XP Docker Test

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64

      - name: Clone dockur/windows Repository
        run: |
          git clone https://github.com/dockur/windows.git windows-xp-docker
          cd windows-xp-docker
          docker build -t windows-xp .

      - name: Create hello.c
        run: |
          echo '#include <stdio.h>' > hello.c
          echo 'int main() { printf("Hello, Windows XP!\\n"); return 0; }' >> hello.c

      - name: Compile hello.c with MinGW
        run: |
          x86_64-w64-mingw32-gcc -o hello.exe hello.c

      - name: Start Windows XP Docker Container
        run: |
          container_id=$(docker run -d windows-xp)
          echo "CONTAINER_ID=$container_id" >> $GITHUB_ENV

      - name: Copy hello.exe to the Windows XP Container
        run: |
          docker cp hello.exe $CONTAINER_ID:C:/hello.exe

      - name: Run hello.exe in Windows XP Container
        run: |
          docker exec $CONTAINER_ID C:/hello.exe > output.txt
          cat output.txt

      - name: Upload Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-output
          path: output.txt
